/* Real business-wallet functions in a synthetic DOM/IDB. No browser, customer,
   Drive, filesystem business document, actual share sheet or clipboard access. */
'use strict';
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict');
const html=fs.readFileSync(path.join(__dirname,'..','index.html'),'utf8');
let source=html.slice(html.indexOf('let __biz='),html.indexOf('/* ═══ v206',html.indexOf('let __biz=')))+'\n'+html.slice(html.indexOf('function smsBiz()'),html.indexOf('let __modalReturnFocus'));
const mutations={
 'all-files':["filter(a=>__bizSelected.has(a.key))","filter(a=>true)"],
 'stale-selection':['__bizSelected.clear();try{const loaded=await loadBiz();','try{const loaded=await loadBiz();'],
 'rerender-reset':['shareBizCard({keepSelection:true});','shareBizCard();'],
 'silent-text':['toast(\'선택 파일 공유 미지원',"await navigator.share({text});toast('선택 파일 공유 미지원"],
 'delete-shift':[".map(k=>k.startsWith('extra:')&&+k.slice(6)>i?'extra:'+(+k.slice(6)-1):k)",'.map(k=>k)'],
 'overwrite-custom':['saved.concat(defaults.filter(p=>!saved.some(s=>s.name===p.name)))','defaults'],
 'empty-text':["typeof t==='string'?t:","typeof t==='string'&&t!==''?t:"],
 'unsafe-image':["typeof a[2]==='string'&&BIZ_IMAGE_RE.test(a[2])","typeof a[2]==='string'"],
 'share-duplicate':['if(__bizSending)return;',''],
 'load-overwrite':['const presets=ps&&ps.length?ps:defaultPresets();','const presets=defaultPresets();'],
 'new-template-stale-text':["await idbSet('biz_text','');",''],
 'stale-callback':['if(!bizViewCurrent(epoch))return;',''],
 'parallel-edit':["if(__bizEditBusy){toast('자료를 저장 중입니다. 완료 후 다시 눌러주세요.');return;}",''],
 'customer-omitted':['...bizCustomerPresets()','...[]'],
 'customer-unverified':['협의한 정산 내역을 확인 부탁드립니다.','미납이 확인되었습니다. 전액 보상하겠습니다. 999,999원을 내세요.'],
 'customer-private-default':['function bizCustomerPresets(){const intro=`안녕하세요, ${COMPANY.name}입니다.`;','function bizCustomerPresets(){const intro=`안녕하세요, ${COMPANY.name}입니다. ${lastAcct().label}`;'],
 'customer-review-note':['실제 작업 상태·금액·일정·입금 여부를 확인해 수정하세요.','']
};
const mutation=process.env.HJ_BIZ_MUTATION;
if(mutation){const pair=mutations[mutation];assert(pair&&source.includes(pair[0]),'mutation anchor missing: '+mutation);source=['rerender-reset','stale-callback'].includes(mutation)?source.replaceAll(pair[0],pair[1]):source.replace(pair[0],pair[1]);}
const clone=v=>v===undefined?undefined:JSON.parse(JSON.stringify(v));
const jpeg=n=>'data:image/jpeg;base64,'+Buffer.from('TEST_IMAGE_'+n).toString('base64');
const imageKeys=['img1','img3','img2','extra:0','extra:1'];
const customerNames=['문의 접수 답변','통화 가능 시간 문의','현장 사진 추가 요청','방문 전 재확인','실측 내용 확인','견적 회신 부탁','자재·색상 확인','작업 전 준비 안내','공정 중간 확인','완료 점검 협의','작업 후 사용 문의','변경 작업 협의 (부드럽게)','변경 작업 협의 (명확하게)','일정 조정 안내 (부드럽게)','일정 조정 안내 (명확하게)','정산 안내 (부드럽게)','정산 확인 요청 (명확하게)','입금 확인 요청','증빙 서류 문의','A/S 방문 협의'];
function environment(initial={}){
 const storage=new Map(Object.entries(clone(initial))),writes=[],shares=[],downloads=[],copies=[],toasts=[],elements=new Map(),inputs=[];
 let body='',checks=[],rejectRead=false,shareError=null,canShare=true,confirmResult=true,shareWait=null,promptValue=null,writeGate=null,gatedKey='';
 function parse(s){body=s;elements.clear();checks=[];for(const m of s.matchAll(/id="([^"]+)"/g))elements.set(m[1],{value:'',textContent:''});
  const ta=elements.get('bizText');if(ta)ta.value=(s.match(/<textarea[^>]*>([\s\S]*?)<\/textarea>/)||[])[1]||'';
  for(const m of s.matchAll(/<input type="checkbox" data-bizcheck="([^"]+)"([^>]*)>/g))checks.push({dataset:{bizcheck:m[1]},checked:m[2].includes(' checked'),disabled:m[2].includes(' disabled')});
  const summary=elements.get('bizSelectionSummary');if(summary)summary.textContent=(s.match(/id="bizSelectionSummary"[^>]*>([\s\S]*?)<\/p>/)||[])[1];
 }
 const doc={getElementById:id=>id==='modalRoot'?{querySelectorAll:()=>checks}:elements.get(id)||null,querySelector:q=>q==='#modalRoot .mfoot'?{style:{},prepend:n=>elements.set(n.id,n)}:null,querySelectorAll:q=>q.includes('data-bizcheck')?checks:[],body:{appendChild:()=>{}},createElement:tag=>{const node={style:{},setAttribute(k,v){this[k]=v;},click(){if(this.download)downloads.push({name:this.download,data:this.href});},remove(){}};if(tag==='input')inputs.push(node);return node;}};
 const ctx=vm.createContext({console,File,Uint8Array,Set,Map,Number,Promise,Error,atob:s=>Buffer.from(s,'base64').toString('binary'),
  COMPANY:{name:'TEST_COMPANY',owner:'TEST_OWNER',tel:'TEST_PHONE',bizno:'TEST_BIZ_NO',business:'TEST_BUSINESS',type:'TEST_TYPE',addr:'TEST_ADDRESS',accounts:[{label:'TEST_ACCOUNT'}]},
  document:doc,window:{},navigator:{canShare:()=>{if(canShare instanceof Error)throw canShare;return canShare;},share:async p=>{shares.push(p);if(shareWait)await shareWait;if(shareError)throw shareError;},clipboard:{writeText:async t=>copies.push(t)}},
  idbGetStrict:async k=>{if(rejectRead)throw new Error('TEST_READ_FAILURE');return clone(storage.get(k));},
  idbSet:async(k,v)=>{writes.push(k);if(writeGate&&k===gatedKey)await writeGate;storage.set(k,clone(v));},
  escapeHtml:s=>String(s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#39;'),
  openModal:(title,s)=>parse(s),closeModal:()=>{},sendDirections:()=>{},toast:s=>toasts.push(s),confirm:()=>confirmResult,prompt:()=>promptValue,location:{href:''}
 });vm.runInContext(source,ctx);
 return {ctx,storage,writes,shares,downloads,copies,toasts,elements,inputs,get body(){return body;},get checks(){return checks;},run:s=>vm.runInContext(s,ctx),rejectRead:()=>{rejectRead=true;},setShare:v=>{canShare=v;},setShareError:e=>{shareError=e;},waitShare:p=>{shareWait=p;},confirm:v=>{confirmResult=v;},prompt:v=>{promptValue=v;},delayWrite:(p,k)=>{writeGate=p;gatedKey=k;},close:()=>{ctx.window.__modalOnClose?.();parse('');}};
}
const seed=()=>({'biz_사업자':jpeg(1),'biz_통장':jpeg(2),'biz_명함':jpeg(3),'biz_extras':[jpeg(4),jpeg(5)],'biz_text':'TEST_EDITED_TEXT','biz_presets':[{name:'사업자 정보',text:'TEST_CUSTOM',customField:'TEST_PRESERVED'},{name:'TEST_CUSTOM_TEMPLATE',text:''}],'biz_presetIdx':1});
let count=0;
async function test(name,fn){await fn();count++;console.log('PASS '+name);}
(async()=>{
 await test('fresh open is read-only and no documents preselected',async()=>{const e=environment(seed());await e.ctx.shareBizCard();assert.equal(e.writes.length,0);assert.equal(e.ctx.bizImageFiles().length,0);assert(e.checks.every(c=>!c.checked));assert.equal(e.elements.get('bizText').value,'TEST_EDITED_TEXT');assert(e.body.includes('value="new:'));});
 for(let mask=0;mask<32;mask++)await test('share/download exact selection mask '+mask,async()=>{
  const e=environment(seed());await e.ctx.shareBizCard();const chosen=imageKeys.filter((k,i)=>mask&(1<<i));e.run('__bizSelected=new Set('+JSON.stringify(chosen)+')');
  const selected=clone(e.ctx.bizSelectedEntries()),files=e.ctx.bizImageFiles();assert.equal(files.length,chosen.length);assert.deepEqual(selected.map(a=>a.key),chosen);
  e.ctx.saveBizImages();assert.deepEqual(e.downloads.map(d=>d.name),selected.map(a=>a.name));assert.deepEqual(e.downloads.map(d=>d.data),selected.map(a=>a.data));
  await e.ctx.sendBiz();assert.equal(e.shares.length,1);assert.deepEqual(clone((e.shares[0].files||[]).map(f=>f.name)),selected.map(a=>a.name));assert.equal(e.shares[0].text,'TEST_EDITED_TEXT');assert.equal(e.copies.length,0);assert(!e.writes.some(k=>/selection|selected/i.test(k)));
 });
 await test('checkbox bindings and quick select only update selection, never send',async()=>{const e=environment(seed());await e.ctx.shareBizCard();e.checks[0].checked=true;e.checks[0].onchange();assert.equal(e.ctx.bizImageFiles().length,1);e.ctx.bizChooseOnly('img3');assert.deepEqual(clone(e.ctx.bizSelectedEntries()).map(a=>a.key),['img3']);assert.equal(e.shares.length,0);e.ctx.bizChooseOnly('');assert.equal(e.ctx.bizImageFiles().length,0);});
 await test('internal rerender preserves current checks and unsaved edits; new open clears checks',async()=>{const e=environment(seed());await e.ctx.shareBizCard();e.run("__bizSelected.add('img3');__biz.text='TEST_UNSAVED_EDIT'");await e.ctx.shareBizCard({keepSelection:true});assert.equal(e.ctx.bizImageFiles().length,1);assert.equal(e.elements.get('bizText').value,'TEST_UNSAVED_EDIT');await e.ctx.selectPreset(0);assert.equal(e.ctx.bizImageFiles().length,1);await e.ctx.shareBizCard();assert.equal(e.ctx.bizImageFiles().length,0);});
 await test('remove preceding extra retains selected original bytes, not adjacent photo',async()=>{const e=environment(seed());await e.ctx.shareBizCard();e.run("__bizSelected=new Set(['img3','extra:1'])");await e.ctx.delBizExtra(0);assert.deepEqual(clone(e.ctx.bizSelectedEntries()).map(a=>a.data),[jpeg(2),jpeg(5)]);});
 await test('removing selected extra cannot select replacement; cancel changes nothing',async()=>{const e=environment(seed());await e.ctx.shareBizCard();e.run("__bizSelected.add('extra:0')");e.confirm(false);await e.ctx.delBizExtra(0);assert.equal(e.ctx.bizImageFiles().length,1);e.confirm(true);await e.ctx.delBizExtra(0);assert.equal(e.ctx.bizImageFiles().length,0);});
 for(const supported of [false,new Error('TEST_CAN_SHARE_ERROR')])await test('file-share unsupported or exception has no text fallback or downloads',async()=>{const e=environment(seed());await e.ctx.shareBizCard();e.ctx.bizChooseOnly('img3');e.setShare(supported);await e.ctx.sendBiz();assert.equal(e.shares.length,0);assert.equal(e.downloads.length,0);assert.equal(e.copies.length,0);});
 for(const name of ['AbortError','NotAllowedError'])await test('share '+name+' has no fallback and unlocks retry',async()=>{const e=environment(seed());await e.ctx.shareBizCard();e.ctx.bizChooseOnly('img1');e.setShareError(Object.assign(new Error('TEST'),{name}));await e.ctx.sendBiz();assert.equal(e.shares.length,1);assert.equal(e.downloads.length,0);assert.equal(e.copies.length,0);e.setShareError(null);await e.ctx.sendBiz();assert.equal(e.shares.length,2);});
 await test('duplicate click while sharing cannot send twice',async()=>{const e=environment(seed());await e.ctx.shareBizCard();let resolve;const pending=new Promise(r=>resolve=r);e.waitShare(pending);const first=e.ctx.sendBiz(),second=e.ctx.sendBiz();assert.equal(e.shares.length,1);resolve();await Promise.all([first,second]);});
 await test('empty message with no attachment never opens share sheet',async()=>{const e=environment(seed());await e.ctx.shareBizCard();e.elements.get('bizText').value='';await e.ctx.sendBiz();assert.equal(e.shares.length,0);});
 await test('custom/deleted/empty templates survive reopening without automatic migration',async()=>{const s=seed();s.biz_text='';const e=environment(s);await e.ctx.shareBizCard();assert.equal(e.elements.get('bizText').value,'');assert.equal(e.run('__biz.presets.length'),2);assert.equal(e.writes.length,0);await e.ctx.addBizRecommended();const saved=clone(e.storage.get('biz_presets'));assert.equal(saved.find(p=>p.name==='사업자 정보').text,'TEST_CUSTOM');assert.equal(saved.find(p=>p.name==='사업자 정보').customField,'TEST_PRESERVED');assert.equal(saved.find(p=>p.name==='TEST_CUSTOM_TEMPLATE').text,'');assert.equal(e.run('defaultPresets().length'),36);const before=saved.length;await e.ctx.addBizRecommended();assert.equal(e.run('__biz.presets.length'),before);});
 await test('new recommendation explicitly selected is saved and retains attachment checks',async()=>{const e=environment(seed());await e.ctx.shareBizCard();e.ctx.bizChooseOnly('img3');await e.ctx.selectBizRecommended(5);assert.equal(e.run('__biz.presets[__biz.presetIdx].name'),'명함 인사');assert.equal(e.ctx.bizImageFiles().length,1);await e.ctx.delPreset();await e.ctx.shareBizCard();assert(!e.storage.get('biz_presets').some(p=>p.name==='명함 인사'));});
 await test('malformed storage read stops without writes or default overwrite',async()=>{const e=environment(seed());e.rejectRead();await e.ctx.shareBizCard();assert.equal(e.body,'');assert.equal(e.writes.length,0);const s=seed();s.biz_presets={private:'TEST_CORRUPTION'};const damaged=environment(s);await damaged.ctx.shareBizCard();assert.equal(damaged.body,'');assert.equal(damaged.writes.length,0);});
 await test('non-raster/remote/attribute-injection images are never rendered or sent',async()=>{const s=seed();s['biz_사업자']='https://TEST_INVALID_DOMAIN/image.jpg';s['biz_통장']='data:image/svg+xml;base64,PHN2Zz4=';s['biz_명함']='data:image/jpeg;base64,AAAA" onerror="TEST_ATTACK';s.biz_extras=[];const e=environment(s);await e.ctx.shareBizCard();assert.equal(e.ctx.bizAttachmentEntries().length,0);assert(!e.body.includes('src="https://'));assert(!e.body.includes('onerror='));assert(e.checks.every(c=>c.disabled));});
 await test('custom template and editor text are HTML-escaped',async()=>{const s=seed();s.biz_presets=[{name:'<img onerror="TEST_ATTACK">',text:'</textarea><script>TEST_ATTACK</script>'}];s.biz_text=s.biz_presets[0].text;const e=environment(s);await e.ctx.shareBizCard();assert(!e.body.includes('<script>TEST_ATTACK'));assert(!e.body.includes('<img onerror='));assert(e.body.includes('&lt;/textarea&gt;'));});
 await test('missing image quick selection never chooses a different registered file',async()=>{const s=seed();s['biz_통장']=null;const e=environment(s);await e.ctx.shareBizCard();e.ctx.bizChooseOnly('img3');assert.equal(e.ctx.bizImageFiles().length,0);});
 await test('new blank template stays blank after close and reopen',async()=>{const e=environment(seed());await e.ctx.shareBizCard();e.prompt('TEST_NEW_TEMPLATE');await e.ctx.addPreset();assert.equal(e.elements.get('bizText').value,'');e.close();await e.ctx.shareBizCard();assert.equal(e.elements.get('bizText').value,'');assert.equal(e.run('__biz.presets[__biz.presetIdx].name'),'TEST_NEW_TEMPLATE');});
 await test('old image decode cannot replace checked document in a new session',async()=>{const e=environment(seed());await e.ctx.shareBizCard();let release;const gate=new Promise(r=>release=r);e.ctx.resizeToDataURL=()=>gate;e.ctx.pickBizImage('img3');const input=e.inputs.at(-1);input.files=[{name:'TEST_FILE'}];const pending=input.onchange();e.close();await e.ctx.shareBizCard();e.ctx.bizChooseOnly('img3');release(jpeg(99));await pending;assert.deepEqual(clone(e.ctx.bizSelectedEntries()).map(a=>a.data),[jpeg(2)]);assert(!e.writes.includes('biz_통장'));});
 await test('late IDB completion cannot change newly edited text or checks',async()=>{const e=environment(seed());await e.ctx.shareBizCard();let release;const gate=new Promise(r=>release=r);e.delayWrite(gate,'biz_text');const pending=e.ctx.selectPreset(0);await Promise.resolve();e.close();await e.ctx.shareBizCard();e.ctx.bizChooseOnly('img3');e.run("__biz.text='TEST_NEW_SESSION_EDIT'");e.elements.get('bizText').value='TEST_NEW_SESSION_EDIT';release();await pending;assert.equal(e.elements.get('bizText').value,'TEST_NEW_SESSION_EDIT');assert.equal(e.ctx.bizImageFiles().length,1);});
 await test('concurrent deletions cannot reverse completion and select another photo',async()=>{const s=seed();s.biz_extras=[jpeg(4),jpeg(5),jpeg(6)];const e=environment(s);await e.ctx.shareBizCard();e.run("__bizSelected.add('extra:2')");let release;const gate=new Promise(r=>release=r);e.delayWrite(gate,'biz_extras');const first=e.ctx.delBizExtra(0),second=e.ctx.delBizExtra(1);assert.equal(e.writes.filter(k=>k==='biz_extras').length,1);release();await Promise.all([first,second]);assert.deepEqual(clone(e.ctx.bizSelectedEntries()).map(a=>a.data),[jpeg(6)]);});
 await test('sharing while a document edit is pending does not open any share sheet',async()=>{const e=environment(seed());await e.ctx.shareBizCard();e.ctx.bizChooseOnly('img3');let release;const gate=new Promise(r=>release=r);e.delayWrite(gate,'biz_text');const pending=e.ctx.selectPreset(0);await e.ctx.sendBiz();assert.equal(e.shares.length,0);release();await pending;});
 await test('twenty customer drafts have unique names, no invented facts or private defaults',async()=>{const e=environment();const drafts=clone(e.ctx.bizCustomerPresets()),all=clone(e.ctx.defaultPresets());assert.deepEqual(drafts.map(p=>p.name),customerNames);assert.deepEqual(all.slice(16),drafts);assert.equal(new Set(all.map(p=>p.name)).size,36);for(const p of drafts){assert(p.text.startsWith('안녕하세요, TEST_COMPANY입니다.'));assert(p.text.split('\n').length>=3&&p.text.split('\n').length<=5);assert(!/[0-9]|@|https?:|무료|무상|전액|보상하겠습니다|미납이 확인|입금되었습니다|법적 절차|지연이자/.test(p.text),p.name);for(const privateValue of ['TEST_OWNER','TEST_PHONE','TEST_BIZ_NO','TEST_ADDRESS','TEST_ACCOUNT'])assert(!p.text.includes(privateValue),p.name+' '+privateValue);}});
 await test('new installation offers 36 editable drafts without storing or sharing on open',async()=>{const e=environment();await e.ctx.shareBizCard();assert.equal(e.run('__biz.presets.length'),36);for(const name of customerNames)assert(e.body.includes(name));assert(e.body.includes('실제 작업 상태·금액·일정·입금 여부를 확인해 수정하세요.'));assert.equal(e.writes.length,0);assert.equal(e.shares.length,0);assert.equal(e.ctx.bizImageFiles().length,0);});
 await test('legacy sixteen drafts stay intact and new customer drafts remain recommendations',async()=>{const s=seed();s.biz_presets=clone(environment().ctx.defaultPresets()).slice(0,16);s.biz_presets[0].text='TEST_LEGACY_CUSTOM';s.biz_text='TEST_LEGACY_DRAFT';const e=environment(s);await e.ctx.shareBizCard();assert.equal(e.run('__biz.presets.length'),16);assert.equal(e.writes.length,0);assert.equal(e.elements.get('bizText').value,'TEST_LEGACY_DRAFT');for(let i=16;i<36;i++)assert(e.body.includes('value="new:'+i+'"'));await e.ctx.addBizRecommended();assert.equal(e.storage.get('biz_presets').length,36);assert.equal(e.storage.get('biz_presets')[0].text,'TEST_LEGACY_CUSTOM');assert.equal(e.elements.get('bizText').value,'TEST_LEGACY_DRAFT');assert.equal(e.shares.length,0);});
 await test('same-name customer customization survives recommendation selection and adding all',async()=>{const s=seed();s.biz_presets.push({name:customerNames[13],text:'TEST_CUSTOMER_CUSTOM',customField:'TEST_CUSTOMER_FIELD'});const e=environment(s);await e.ctx.shareBizCard();const index=e.ctx.defaultPresets().findIndex(p=>p.name===customerNames[13]);await e.ctx.selectBizRecommended(index);assert.equal(e.elements.get('bizText').value,'TEST_CUSTOMER_CUSTOM');await e.ctx.addBizRecommended();const matches=e.storage.get('biz_presets').filter(p=>p.name===customerNames[13]);assert.equal(matches.length,1);assert.equal(matches[0].text,'TEST_CUSTOMER_CUSTOM');assert.equal(matches[0].customField,'TEST_CUSTOMER_FIELD');assert.equal(e.shares.length,0);});
 await test('deleted customer draft is not reinserted on reopen',async()=>{const e=environment(seed());await e.ctx.shareBizCard();const index=e.ctx.defaultPresets().findIndex(p=>p.name===customerNames[0]);await e.ctx.selectBizRecommended(index);await e.ctx.delPreset();e.close();const writes=e.writes.length;await e.ctx.shareBizCard();assert.equal(e.writes.length,writes);assert(!e.storage.get('biz_presets').some(p=>p.name===customerNames[0]));assert(e.body.includes('value="new:'+index+'"'));});
 for(const name of customerNames)await test('explicit customer recommendation only prepares editable draft: '+name,async()=>{const e=environment(seed());await e.ctx.shareBizCard();e.ctx.bizChooseOnly('img2');const before=clone(e.ctx.bizSelectedEntries());const index=e.ctx.defaultPresets().findIndex(p=>p.name===name);await e.ctx.selectBizRecommended(index);assert.equal(e.run('__biz.presets[__biz.presetIdx].name'),name);assert.equal(e.elements.get('bizText').value,e.ctx.defaultPresets()[index].text);assert.deepEqual(clone(e.ctx.bizSelectedEntries()),before);assert.equal(e.storage.get('biz_presets').length,3);assert.equal(e.shares.length,0);assert.equal(e.downloads.length,0);assert.equal(e.copies.length,0);e.elements.get('bizText').value='TEST_CUSTOMER_FINAL';await e.ctx.savePresetEdit();e.close();await e.ctx.shareBizCard();assert.equal(e.elements.get('bizText').value,'TEST_CUSTOMER_FINAL');assert.equal(e.ctx.bizImageFiles().length,0);});
 console.log('biz-select: '+count+'/'+count+' PASS');
})().catch(e=>{console.error(e.stack);process.exitCode=1;});
