'use strict';
/* Task 3 RED: native IndexedDB pointer-first reload and legacy aptOrder schema. */
const assert=require('node:assert/strict');const fs=require('node:fs');const http=require('node:http');const path=require('node:path');
function playwright(){for(const p of ['playwright',path.resolve(path.dirname(process.execPath),'..','node_modules','playwright'),'/opt/node22/lib/node_modules/playwright']){try{return require(p);}catch(_){}}throw Error('playwright unavailable');}
const {chromium}=playwright(),root=path.resolve(__dirname,'..'),source=fs.readFileSync(path.join(root,'index.html'),'utf8');
for(const name of ['executePaidWorkGate','transitionAptOrderWithGate','updateCommercialTerms','paidCommitWriteAtomic','readPaidCommitSnapshot','resolvePaidCommitState'])assert.match(source,new RegExp('(?:async\\s+)?function\\s+'+name+'\\s*\\('),'missing native/legacy Task 3 function '+name);
const TERMS={workKind:'repair',scope:'욕실 누수 보수',exclusions:['타일 전체 교체'],vatMode:'included',quotedAmount:250000,validUntil:'2026-09-30',scheduleWindow:'2026-09-05 오전'};
const receipt=id=>({receiptId:'receipt_'+id,subjectType:'aptOrder',subjectId:id,approvedTermsSha256:'a'.repeat(64),approvalEvidenceType:'quote-file',approvalEvidenceFileId:'drive_'+id,approvalEvidenceSha256:'b'.repeat(64),approvedAt:'2026-08-31T12:00:00+09:00',approvedByRole:'management-office',issuedAt:'2026-08-31T12:00:01+09:00',receiptHmac:'c'.repeat(64)});
function server(){const s=http.createServer((q,r)=>{const p=decodeURIComponent(new URL(q.url,'http://127.0.0.1').pathname),f=path.resolve(root,'.'+p);if(f!==root&&!f.startsWith(root+path.sep)){r.writeHead(403);r.end();return;}fs.stat(f,(e,st)=>{const t=!e&&st.isDirectory()?path.join(f,'index.html'):f;fs.readFile(t,(x,b)=>{if(x){r.writeHead(404);r.end();return;}r.writeHead(200,{'Content-Type':path.extname(t)==='.js'?'text/javascript':'text/html; charset=utf-8','Cache-Control':'no-store'});r.end(b);});});});return new Promise((ok,no)=>{s.once('error',no);s.listen(0,'127.0.0.1',()=>ok(s));});}
async function open(browser,url,context){context=context||await browser.newContext({serviceWorkers:'block'});if(!context.__init){await context.addInitScript(()=>localStorage.setItem('hj_onboard_done','1'));context.__init=true;}const page=await context.newPage();await page.route('https://**/*',r=>r.abort());await page.goto(url,{waitUntil:'domcontentloaded'});await page.waitForFunction(()=>window.__hjRestoreDone&&typeof executePaidWorkGate==='function');await page.evaluate(()=>Promise.resolve(window.__hjRestoreDone));return{context,page};}
(async()=>{const s=await server(),url=`http://127.0.0.1:${s.address().port}/index.html`,browser=await chromium.launch(process.env.PLAYWRIGHT_EXECUTABLE?{executablePath:process.env.PLAYWRIGHT_EXECUTABLE}:{});try{
 const a=await open(browser,url),page=a.page,b=await open(browser,url,a.context);
 const result=await page.evaluate(async({terms,receipts})=>{
  clearTimeout(__idbSaveTimer);__idbSaveTimer=null;state._demo=false;state.projects=[];state.files=[];state.quotes=[];state.notes=[];state.schedule=[];state.calendarImports=[];
  state.aptOrders=[{id:'legacy_recv',status:'recv'},{id:'legacy_visit',status:'visit'},{id:'legacy_work',status:'work'},{id:'legacy_done',status:'done'},{id:'legacy_billed',status:'billed'},{id:'legacy_paid',status:'paid'},{id:'intake_recv',status:'recv',source:'office-intake',sourceRequestId:'request_1'}];
  state.payLog=[{d:'2026-08-31',project:'기존 단지',amt:100000}];__paidCommitPointerKey=null;__paidApprovalConsumptions.clear();
  let validationSerial=0;validateCommercialApproval=async({commercialApproval})=>Object.freeze({receiptId:commercialApproval.receiptId,nonce:'nonce_'+commercialApproval.receiptId+'_'+(++validationSerial),serverNowKst:'2026-08-31T12:00:00+09:00',verifyExpiresAtKst:'2026-08-31T12:01:00+09:00',useBeforeMonotonicMs:Number.MAX_SAFE_INTEGER});
  const closedBefore=JSON.parse(JSON.stringify(state.aptOrders.filter(o=>['done','billed','paid'].includes(o.status))));
  const transitioned=[];for(const [id,target] of [['legacy_recv','visit'],['legacy_visit','work'],['legacy_work','billed'],['intake_recv','visit']])transitioned.push(await transitionAptOrderWithGate({orderId:id,targetState:target,commercialTerms:terms,commercialApproval:receipts[id]}));
  const created=await executePaidWorkGate({commandKind:'create-order',subjectType:'aptOrder',subjectId:'new_schema_order',targetState:'visit',commercialTerms:terms,commercialApproval:receipts.new_schema_order,createDraft:Object.freeze({id:'new_schema_order',state:'visit',source:'manual-paid-diagnosis'})});
  const changed=await updateCommercialTerms('legacy_recv',{...terms,quotedAmount:300000});let oldApproval='',compound='';try{await transitionAptOrderWithGate({orderId:'legacy_recv',targetState:'work',commercialTerms:terms,commercialApproval:receipts.legacy_recv});}catch(e){oldApproval=String(e.code||e.message||e);}try{await transitionAptOrderWithGate({orderId:'legacy_recv',targetState:'work',commercialTerms:terms,commercialApproval:receipts.legacy_recv,nextTerms:{...terms,quotedAmount:310000}});}catch(e){compound=String(e.code||e.message||e);}
  const pointer=await idbGet('paid_commit_pointer'),journal=await idbGet('paid_commit_journal'),generation=await idbGet(pointer);
  return{closedBefore,closedAfter:JSON.parse(JSON.stringify(state.aptOrders.filter(o=>['legacy_done','legacy_billed','legacy_paid'].includes(o.id)))),transitioned,created,changed,oldApproval,compound,payLog:state.payLog,pointer,journal,generation,tabStamp:__tabStamp};
 },{terms:TERMS,receipts:{legacy_recv:receipt('legacy_recv'),legacy_visit:receipt('legacy_visit'),legacy_work:receipt('legacy_work'),intake_recv:receipt('intake_recv'),new_schema_order:receipt('new_schema_order')}});
 assert.deepEqual(result.closedAfter,result.closedBefore,'closed legacy orders stay readable without backfill');
 assert.deepEqual(result.transitioned.map(o=>o.status),['visit','work','billed','visit']);for(const o of result.transitioned){assert.equal(o.commercialGateVersion,1);assert.equal(o.commercialApproval.receiptHmac,'c'.repeat(64));}
 assert.equal(result.created.status,'visit');assert.equal(Object.hasOwn(result.created,'state'),false,'gate input state is projected to authoritative status');assert.equal(result.created.status in await page.evaluate(()=>APT_STAT),true,'existing rendering recognizes the created status');
 assert.equal(result.changed.order.commercialApproval,null);assert.equal(result.changed.order.commercialApprovalAudit.at(-1).previousApproval.receiptId,'receipt_legacy_recv');assert.match(result.oldApproval,/commercial terms changed/,'old receipt/terms cannot authorize after terms replacement');assert.match(result.compound,/compound-command-not-allowed/);assert.deepEqual(result.payLog,[{d:'2026-08-31',project:'기존 단지',amt:100000}]);
 assert.equal(result.journal.current,result.pointer);assert.equal(result.generation.savedAt,result.journal.committedAt);assert.equal(result.tabStamp,result.generation.savedAt);

 const snapshotRead=await page.evaluate(async()=>{const original=IDBDatabase.prototype.transaction,modes=[];IDBDatabase.prototype.transaction=function(){modes.push(arguments.length>1?arguments[1]:'readonly');return original.apply(this,arguments);};try{const value=await readPaidCommitSnapshot();return{modes,pointer:value.pointer,journalCurrent:value.journal&&value.journal.current,generationSavedAt:value.generation&&value.generation.savedAt};}finally{IDBDatabase.prototype.transaction=original;}});
 assert.deepEqual(snapshotRead.modes,['readonly'],'pointer, journal, generation, and appState are read in one native readonly transaction');assert.equal(snapshotRead.pointer,snapshotRead.journalCurrent);assert.equal(snapshotRead.generationSavedAt,result.generation.savedAt);

 const nativeAbort=await page.evaluate(async()=>{const before={pointer:await idbGet('paid_commit_pointer'),journal:await idbGet('paid_commit_journal'),app:await idbGet('appState')},candidate=structuredClone(await idbGet(before.pointer));candidate.savedAt=new Date(Date.parse(candidate.savedAt)+1000).toISOString();let error='';try{await paidCommitWriteAtomic(candidate,'paid_commit_generation:wrong','paid_commit_generation:abort_probe');}catch(e){error=String(e.message||e);}return{before,after:{pointer:await idbGet('paid_commit_pointer'),journal:await idbGet('paid_commit_journal'),app:await idbGet('appState'),probe:await idbGet('paid_commit_generation:abort_probe')},error};});
 assert.match(nativeAbort.error,/conflict|pointer|abort/i);assert.deepEqual(nativeAbort.after,{...nativeAbort.before,probe:undefined},'real IDB abort leaves no partial write');

 await page.evaluate(()=>{clearTimeout(__idbSaveTimer);__idbSaveTimer=null;});
 const stale=await b.page.evaluate(async()=>{
  const old=__paidCommitPointerKey,read=()=>idbGet('appState'),beforePointer=await idbGet('paid_commit_pointer'),beforeJournal=await idbGet('paid_commit_journal'),beforeGeneration=await idbGet(beforePointer);
  __tabStale=false;state.notes=[{id:'stale-persist'}];persistLocal();await new Promise(r=>setTimeout(r,950));const persist=await read();
  __tabStale=false;state.notes=[{id:'stale-pagehide'}];window.dispatchEvent(new Event('pagehide'));await new Promise(r=>setTimeout(r,80));const pagehide=await read();
  __tabStale=false;state.notes=[{id:'stale-visibility'}];Object.defineProperty(document,'visibilityState',{configurable:true,value:'hidden'});document.dispatchEvent(new Event('visibilitychange'));await new Promise(r=>setTimeout(r,80));const visibility=await read();
  __tabStale=false;state.notes=[{id:'stale-intake'}];const intakeOk=await officeIntakePersistNow(),intake=await read();
  __tabStale=false;state.files=[];cloudApiListFiles=async()=>({ok:true,files:[{id:'stale_photo',name:'stale.jpg',mimeType:'image/jpeg',size:100}]});await relayLoadDriveFiles(true);await new Promise(r=>setTimeout(r,80));const relay=await read();
  const afterPointer=await idbGet('paid_commit_pointer');return{old,persist,pagehide,visibility,intakeOk,intake,relay,before:{pointer:beforePointer,journal:beforeJournal,generation:beforeGeneration},after:{pointer:afterPointer,journal:await idbGet('paid_commit_journal'),generation:await idbGet(afterPointer)}};
 });
 assert.equal(stale.old,null);for(const key of ['persist','pagehide','visibility','intake','relay']){assert.equal(stale[key].aptOrders.some(o=>o.id==='new_schema_order'),true,key+' cannot clobber the paid commit');assert.equal((stale[key].notes||[]).some(n=>String(n.id||'').startsWith('stale-')),false,key+' does not persist stale live notes');}assert.equal(stale.intakeOk,false,'stale immediate writer reports rejection');assert.equal(stale.relay.files.some(f=>f.driveId==='stale_photo'),false,'silent relay recovery cannot bypass the pointer guard');
 assert.deepEqual(stale.after,stale.before,'stale guarded transaction abort leaves pointer, journal, and current generation unchanged');

 await page.evaluate(async()=>{const old=serializeData();old.aptOrders=[];old.savedAt='2026-08-31T00:00:00.000Z';await idbSet('appState',old);});await page.reload({waitUntil:'domcontentloaded'});await page.waitForFunction(()=>window.__hjRestoreDone&&Array.isArray(state.aptOrders)&&state.aptOrders.some(o=>o.id==='new_schema_order'));
 const reload=await page.evaluate(async()=>({ids:state.aptOrders.map(o=>o.id),pointer:await idbGet('paid_commit_pointer'),generation:await idbGet(await idbGet('paid_commit_pointer')),stamp:__tabStamp,source:window.__hjRestoreSource}));assert.equal(reload.ids.filter(id=>id==='new_schema_order').length,1);assert.equal(reload.stamp,reload.generation.savedAt);assert.equal(reload.source,'paid-generation');

 const malformed=await page.evaluate(async()=>{const legacy=structuredClone(await idbGet('appState'));legacy.aptOrders=[{id:'fallback',status:'done'}];legacy.savedAt='2026-08-31T00:00:03.000Z';await idbSet('appState',legacy);const key='paid_commit_generation:bad',j={schemaVersion:1,current:key,previous:null,committedAt:legacy.savedAt,generations:[key],maxGenerations:PAID_COMMIT_MAX_GENERATIONS};const run=async(journal,generation)=>{await idbSet('paid_commit_pointer',key);await idbSet('paid_commit_journal',journal);if(generation!==undefined)await idbSet(key,generation);const r=await resolvePaidCommitState();return{source:r.source,ids:r.data.aptOrders.map(o=>o.id)};};return{missing:await run(j,undefined),mismatch:await run({...j,current:'paid_commit_generation:other'},legacy),office:await run(j,{...legacy,office_ops_cache:{secret:true}}),field:await run(j,{...legacy,aptOrders:'bad'})};});for(const v of Object.values(malformed))assert.deepEqual(v,{source:'legacy-appState',ids:['fallback']});

 await page.evaluate(async()=>{const legacy=structuredClone(await idbGet('appState'));legacy.notes=[{id:'malformed-fallback'}];legacy.savedAt='2026-08-31T00:00:04.000Z';await idbSet('appState',legacy);await idbSet('paid_commit_pointer','malformed-pointer');await idbSet('paid_commit_journal',{bad:true});});await page.reload({waitUntil:'domcontentloaded'});await page.waitForFunction(()=>window.__hjRestoreDone);await page.evaluate(()=>Promise.resolve(window.__hjRestoreDone));
 const recoveredMalformed=await page.evaluate(async()=>{state._demo=false;state.notes=[{id:'malformed-recovered'}];const ok=await guardedPersistCurrentState();return{ok,pointer:await idbGet('paid_commit_pointer'),journal:await idbGet('paid_commit_journal'),app:await idbGet('appState'),source:window.__hjRestoreSource,recoveryFlag:__paidCommitRecoveryMalformedPointer};});
 assert.equal(recoveredMalformed.source,'legacy-appState');assert.equal(recoveredMalformed.ok,true,'guarded persistence repairs the exact malformed pointer observed at boot');assert.equal(recoveredMalformed.pointer,undefined);assert.equal(recoveredMalformed.journal,undefined);assert.deepEqual(recoveredMalformed.app.notes,[{id:'malformed-recovered'}]);assert.equal(recoveredMalformed.recoveryFlag,false);

 const isolated=await open(browser,url),deep=await isolated.page.evaluate(async({terms,makeReceipt})=>{
  clearTimeout(__idbSaveTimer);__idbSaveTimer=null;state._demo=false;state.projects=[];state.files=[];state.quotes=[];state.notes=[];state.schedule=[];state.calendarImports=[];state.aptOrders=[];state.payLog=[];
  await idbDel('appState');await idbDel('paid_commit_pointer');await idbDel('paid_commit_journal');__paidCommitPointerKey=null;__paidApprovalConsumptions.clear();
  let nonceSerial=0;validateCommercialApproval=async({commercialApproval})=>Object.freeze({receiptId:commercialApproval.receiptId,nonce:'deep_nonce_'+(++nonceSerial),serverNowKst:'2026-08-31T12:00:00+09:00',verifyExpiresAtKst:'2026-08-31T12:01:00+09:00',useBeforeMonotonicMs:Number.MAX_SAFE_INTEGER});
  const rec=id=>({...makeReceipt,receiptId:'receipt_'+id,subjectId:id,approvalEvidenceFileId:'drive_'+id});
  const capture=async work=>{try{return{ok:true,value:await work()};}catch(e){return{ok:false,error:String(e.code||e.message||e)};}};
  const invalidCommands=[];
  invalidCommands.push(await capture(()=>executePaidWorkGate({commandKind:'create-order',subjectType:'project',subjectId:'bad',targetState:'visit',commercialTerms:terms,commercialApproval:rec('bad'),createDraft:Object.freeze({id:'bad',state:'visit'})})));
  invalidCommands.push(await capture(()=>executePaidWorkGate({commandKind:'create-order',subjectType:'aptOrder',subjectId:'bad',targetState:'work',commercialTerms:terms,commercialApproval:rec('bad'),createDraft:Object.freeze({id:'bad',state:'visit'})})));
  invalidCommands.push(await capture(()=>executePaidWorkGate({commandKind:'create-order',subjectType:'aptOrder',subjectId:'bad',targetState:'visit',commercialTerms:terms,commercialApproval:rec('bad'),createDraft:{id:'bad',state:'visit'}})));
  invalidCommands.push(await capture(()=>executePaidWorkGate({commandKind:'transition-state',subjectType:'aptOrder',subjectId:'bad',targetState:'work',commercialTerms:terms,commercialApproval:rec('bad'),createDraft:Object.freeze({id:'bad',state:'visit'})})));
  const mutationState=async()=>({live:JSON.stringify({aptOrders:state.aptOrders,notes:state.notes}),pointer:(await idbGet('paid_commit_pointer'))||null,journal:(await idbGet('paid_commit_journal'))||null,appState:(await idbGet('appState'))||null,consumed:Array.from(__paidApprovalConsumptions)}),failureBaseline=await mutationState(),failures=[];
  const realSnapshot=hjSnapshot;hjSnapshot=async()=>false;failures.push({kind:'snapshot',outcome:await capture(()=>durablePaidMutation({verification:{receiptId:'receipt_fail_snapshot',nonce:'fail_snapshot',useBeforeMonotonicMs:Number.MAX_SAFE_INTEGER},snapshotLabel:'유상 실패',mutateDraft:next=>next.notes.push({id:'bad'})})),state:await mutationState()});hjSnapshot=realSnapshot;
  failures.push({kind:'validation',outcome:await capture(()=>durablePaidMutation({verification:{receiptId:'receipt_fail_validation',nonce:'fail_validation',useBeforeMonotonicMs:Number.MAX_SAFE_INTEGER},snapshotLabel:'유상 실패',mutateDraft:next=>{next.aptOrders='bad';}})),state:await mutationState()});
  failures.push({kind:'serialization',outcome:await capture(()=>durablePaidMutation({verification:{receiptId:'receipt_fail_serialization',nonce:'fail_serialization',useBeforeMonotonicMs:Number.MAX_SAFE_INTEGER},snapshotLabel:'유상 실패',mutateDraft:next=>next.notes.push(1n)})),state:await mutationState()});
  const realWriter=paidCommitWriteAtomic;paidCommitWriteAtomic=async()=>{throw Error('injected IDB transaction failure');};failures.push({kind:'transaction',outcome:await capture(()=>durablePaidMutation({verification:{receiptId:'receipt_fail_transaction',nonce:'fail_transaction',useBeforeMonotonicMs:Number.MAX_SAFE_INTEGER},snapshotLabel:'유상 실패',mutateDraft:next=>next.notes.push({id:'bad'})})),state:await mutationState()});paidCommitWriteAtomic=realWriter;
  const empty=await executePaidWorkGate({commandKind:'create-order',subjectType:'aptOrder',subjectId:'empty_paid',targetState:'visit',commercialTerms:terms,commercialApproval:rec('empty_paid'),createDraft:Object.freeze({id:'empty_paid',state:'visit'})});
  const snapsAfterEmpty=(await idbGet('hj_snaps'))||[];
  const aptOnly=await transitionAptOrderWithGate({orderId:'empty_paid',targetState:'work',commercialTerms:terms,commercialApproval:rec('empty_paid')});
  const concurrent=await Promise.all(['concurrent_one','concurrent_two'].map(id=>executePaidWorkGate({commandKind:'create-order',subjectType:'aptOrder',subjectId:id,targetState:'visit',commercialTerms:terms,commercialApproval:rec(id),createDraft:Object.freeze({id,state:'visit'})})));
  for(let index=0;index<PAID_COMMIT_MAX_GENERATIONS+2;index++){const r=rec('empty_paid');r.receiptId='receipt_bound_'+index;await transitionAptOrderWithGate({orderId:'empty_paid',targetState:index%2?'visit':'work',commercialTerms:terms,commercialApproval:r});}
  const journal=await idbGet('paid_commit_journal'),keys=await new Promise((resolve,reject)=>{const o=indexedDB.open('hyeonjang-db',1);o.onerror=()=>reject(o.error);o.onsuccess=()=>{const db=o.result,tx=db.transaction('kv','readonly'),g=tx.objectStore('kv').getAllKeys();g.onsuccess=()=>{db.close();resolve(g.result.map(String));};g.onerror=()=>reject(g.error);};});
  const exactVerification={receiptId:'receipt_deadline_exact',nonce:'deadline_exact',useBeforeMonotonicMs:60000};let now=60000;const originalNow=performance.now;Object.defineProperty(performance,'now',{configurable:true,value:()=>now});
  const exact=await durablePaidMutation({verification:exactVerification,snapshotLabel:'유상 경계',mutateDraft:next=>{next.notes.push({id:'deadline-exact'});return 'exact';}});
  const originalSnapshot=hjSnapshot;hjSnapshot=async(...args)=>{const ok=await originalSnapshot(...args);now=60001;return ok;};let late='';try{await durablePaidMutation({verification:{receiptId:'receipt_deadline_late',nonce:'deadline_late',useBeforeMonotonicMs:60000},snapshotLabel:'유상 지연',mutateDraft:next=>next.notes.push({id:'deadline-late'})});}catch(e){late=String(e.message||e);}hjSnapshot=originalSnapshot;Object.defineProperty(performance,'now',{configurable:true,value:originalNow.bind(performance)});
  await durablePaidMutation({verification:{receiptId:'receipt_duplicate',nonce:'duplicate_nonce',useBeforeMonotonicMs:Number.MAX_SAFE_INTEGER},snapshotLabel:'유상 ACK',mutateDraft:next=>next.notes.push({id:'dup-one'})});let duplicate='';try{await durablePaidMutation({verification:{receiptId:'receipt_duplicate',nonce:'duplicate_nonce',useBeforeMonotonicMs:Number.MAX_SAFE_INTEGER},snapshotLabel:'유상 ACK 재사용',mutateDraft:next=>next.notes.push({id:'dup-two'})});}catch(e){duplicate=String(e.message||e);}const reverified=await durablePaidMutation({verification:{receiptId:'receipt_duplicate',nonce:'duplicate_nonce_new',useBeforeMonotonicMs:Number.MAX_SAFE_INTEGER},snapshotLabel:'유상 ACK 재검증',mutateDraft:next=>{next.notes.push({id:'dup-new'});return 'new';}});
  let duplicateTransactions=0;const countedWriter=paidCommitWriteAtomic;paidCommitWriteAtomic=async(...args)=>{duplicateTransactions++;return countedWriter(...args);};const sameVerification={receiptId:'receipt_duplicate_concurrent',nonce:'duplicate_nonce_concurrent',useBeforeMonotonicMs:Number.MAX_SAFE_INTEGER};const concurrentDuplicate=await Promise.allSettled([durablePaidMutation({verification:sameVerification,snapshotLabel:'유상 ACK 동시 1',mutateDraft:next=>{next.notes.push({id:'dup-concurrent-one'});return 'one';}}),durablePaidMutation({verification:sameVerification,snapshotLabel:'유상 ACK 동시 2',mutateDraft:next=>{next.notes.push({id:'dup-concurrent-two'});return 'two';}})]);paidCommitWriteAtomic=countedWriter;
  const originalRender=render;render=()=>{throw Error('render injected');};const renderReceipt=rec('empty_paid');renderReceipt.receiptId='receipt_render_failure';let renderResult='',renderError='';try{renderResult=(await transitionAptOrderWithGate({orderId:'empty_paid',targetState:'work',commercialTerms:terms,commercialApproval:renderReceipt})).status;}catch(e){renderError=String(e.message||e);}render=originalRender;const banner=!!document.getElementById('hjPaidCommitRecovery'),renderPointer=await idbGet('paid_commit_pointer'),renderGeneration=await idbGet(renderPointer);
  let release;const queuedPointerBefore=await idbGet('paid_commit_pointer'),blocker=withAppStateWriteLock(()=>new Promise(resolve=>{release=resolve;}));state.notes=[{id:'queued-old'}];const queued=guardedPersistCurrentState();state.notes=[{id:'queued-latest'}];await Promise.resolve();release();await blocker;const queuedOk=await queued,queuedSaved=await idbGet('appState'),queuedPointer=await idbGet('paid_commit_pointer'),queuedJournal=await idbGet('paid_commit_journal'),queuedGeneration=await idbGet(queuedPointer);
  const officeOwnBefore=Object.hasOwn(state,'officeIntake');delete state.officeIntake;const pureCandidate=serializeData(),officeOwnAfter=Object.hasOwn(state,'officeIntake');
  return{invalidCommands,mutationState:failureBaseline,failures,empty,aptOnly,emptySnapshot:snapsAfterEmpty.at(-1),concurrent,ids:state.aptOrders.map(o=>o.id),journal,generationKeys:keys.filter(k=>k.startsWith('paid_commit_generation:')),exact,late,notes:state.notes,duplicate,reverified,duplicateTransactions,concurrentDuplicate:concurrentDuplicate.map(row=>({status:row.status,value:row.value,error:row.reason&&String(row.reason.message||row.reason)})),renderResult,renderError,banner,renderGeneration,queuedOk,queuedSaved,queuedPointerBefore,queuedPointer,queuedJournal,queuedGeneration,officeOwnBefore,officeOwnAfter,pureOfficeIntake:pureCandidate.officeIntake};
 },{terms:TERMS,makeReceipt:receipt('template')});
 for(const invalid of deep.invalidCommands)assert.equal(invalid.ok,false,'invalid paid gate commands fail before mutation');for(const failure of deep.failures){assert.equal(failure.outcome.ok,false,failure.kind+' failure is surfaced');assert.deepEqual(failure.state,deep.mutationState,failure.kind+' leaves live state, pointer, journal, appState, and ACK consumption unchanged');}assert.equal(deep.empty.status,'visit');assert.equal(deep.emptySnapshot.data.aptOrders.length,0,'first paid create snapshots a completely empty pre-state');assert.equal(deep.aptOnly.status,'work','aptOrders-only paid transition can snapshot and commit');assert.deepEqual(deep.ids.slice().sort(),['concurrent_one','concurrent_two','empty_paid'],'concurrent paid candidates retain both orders');assert.ok(deep.journal.generations.length<=deep.journal.maxGenerations);assert.ok(deep.generationKeys.length<=deep.journal.maxGenerations,'generation records stay bounded');assert.equal(deep.exact,'exact','deadline equality is accepted');assert.match(deep.late,/stale/);assert.equal(deep.notes.some(n=>n.id==='deadline-late'),false,'post-snapshot +1ms rejects before mutation');assert.match(deep.duplicate,/consumed/);assert.equal(deep.reverified,'new','same receipt succeeds with a newly verified nonce');assert.equal(deep.duplicateTransactions,1,'concurrent duplicate ACK reaches the native transaction writer exactly once');assert.deepEqual(deep.concurrentDuplicate.map(row=>row.status),['fulfilled','rejected']);assert.match(deep.concurrentDuplicate[1].error,/consumed/);assert.equal(deep.notes.some(n=>n.id==='dup-concurrent-two'),false,'rejected concurrent duplicate never reaches candidate mutation');assert.equal(deep.renderError,'');assert.equal(deep.renderResult,'work');assert.equal(deep.banner,true);assert.equal(deep.renderGeneration.aptOrders.find(o=>o.id==='empty_paid').status,'work','render failure keeps committed generation');assert.equal(deep.queuedOk,true);assert.deepEqual(deep.queuedSaved.notes,[{id:'queued-latest'}],'guard serializes latest live state only after lock release');assert.equal(deep.queuedPointer,deep.queuedPointerBefore,'ordinary guarded save retains the current generation identity');assert.deepEqual(deep.queuedGeneration,deep.queuedSaved,'ordinary guarded save atomically advances appState and the current generation together');assert.equal(deep.queuedJournal.committedAt,deep.queuedSaved.savedAt,'ordinary guarded save advances journal timestamp with the same payload');assert.equal(deep.officeOwnBefore,true);assert.equal(deep.officeOwnAfter,false,'candidate serialization does not normalize missing officeIntake onto live state');assert.deepEqual(deep.pureOfficeIntake,{inbox:[],outbox:[],operationalErrors:[],cursor:'',lastSyncAt:'',lastError:''});
 await isolated.page.reload({waitUntil:'domcontentloaded'});await isolated.page.waitForFunction(()=>window.__hjRestoreDone);await isolated.page.evaluate(()=>Promise.resolve(window.__hjRestoreDone));const guardedReload=await isolated.page.evaluate(()=>({notes:state.notes,paid:state.aptOrders.find(o=>o.id==='empty_paid'),source:window.__hjRestoreSource}));assert.deepEqual(guardedReload.notes,[{id:'queued-latest'}]);assert.equal(guardedReload.paid.commercialGateVersion,1);assert.equal(guardedReload.source,'paid-generation');
 await isolated.context.close();

 /* Fix round 1 RED: each result below exercises the real browser queue and native IndexedDB. */
 const reviewFailures=[];

 const raceA=await open(browser,url);const raceSeed=await raceA.page.evaluate(async({terms,approval})=>{
  clearTimeout(__idbSaveTimer);__idbSaveTimer=null;state._demo=false;state.projects=[];state.files=[];state.quotes=[];state.notes=[];state.schedule=[];state.calendarImports=[];state.aptOrders=[];state.payLog=[];state.officeIntake={inbox:[],outbox:[],operationalErrors:[],cursor:'',lastSyncAt:'',lastError:''};
  await idbDel('appState');await idbDel('paid_commit_pointer');await idbDel('paid_commit_journal');await idbDel('hj_snaps');__paidCommitPointerKey=null;__paidApprovalConsumptions.clear();
  validateCommercialApproval=async({commercialApproval})=>Object.freeze({receiptId:commercialApproval.receiptId,nonce:'nonce_'+commercialApproval.receiptId,serverNowKst:'2026-08-31T12:00:00+09:00',verifyExpiresAtKst:'2026-08-31T12:01:00+09:00',useBeforeMonotonicMs:Number.MAX_SAFE_INTEGER});
  await executePaidWorkGate({commandKind:'create-order',subjectType:'aptOrder',subjectId:'critical_order',targetState:'visit',commercialTerms:terms,commercialApproval:approval,createDraft:Object.freeze({id:'critical_order',state:'visit'})});clearTimeout(__idbSaveTimer);__idbSaveTimer=null;
  return{pointer:await idbGet('paid_commit_pointer'),stamp:__tabStamp};
 },{terms:TERMS,approval:receipt('critical_order')});
 const raceB=await open(browser,url,raceA.context);const raceLoaded=await raceB.page.evaluate(()=>({pointer:__paidCommitPointerKey,stamp:__tabStamp}));await new Promise(resolve=>setTimeout(resolve,20));
 const ordinary=await raceA.page.evaluate(async()=>{clearTimeout(__idbSaveTimer);__idbSaveTimer=null;state.notes=[{id:'fresh-from-a'}];const pointerBefore=await idbGet('paid_commit_pointer'),ok=await guardedPersistCurrentState(),pointerAfter=await idbGet('paid_commit_pointer');return{ok,pointerBefore,pointerAfter,stamp:__tabStamp};});
 await raceB.page.waitForFunction(()=>__tabStale===true,null,{timeout:5000});
 const raceBefore=await raceA.page.evaluate(async()=>{const pointer=await idbGet('paid_commit_pointer');return{pointer,journal:await idbGet('paid_commit_journal'),generation:await idbGet(pointer),appState:await idbGet('appState')};});
 const staleAttempt=await raceB.page.evaluate(async({terms,approval})=>{clearTimeout(__idbSaveTimer);__idbSaveTimer=null;let writerCalls=0,error='';const original=paidCommitWriteAtomic;paidCommitWriteAtomic=async(...args)=>{writerCalls++;return original(...args);};validateCommercialApproval=async({commercialApproval})=>Object.freeze({receiptId:commercialApproval.receiptId,nonce:'nonce_stale_same_pointer',serverNowKst:'2026-08-31T12:00:00+09:00',verifyExpiresAtKst:'2026-08-31T12:01:00+09:00',useBeforeMonotonicMs:Number.MAX_SAFE_INTEGER});try{await transitionAptOrderWithGate({orderId:'critical_order',targetState:'work',commercialTerms:terms,commercialApproval:approval});}catch(e){error=String(e.code||e.message||e);}finally{paidCommitWriteAtomic=original;}return{writerCalls,error,tabStale:__tabStale,consumed:Array.from(__paidApprovalConsumptions)};},{terms:TERMS,approval:{...receipt('critical_order'),receiptId:'receipt_critical_stale'}});
 const raceAfterStale=await raceA.page.evaluate(async()=>{const pointer=await idbGet('paid_commit_pointer');return{pointer,journal:await idbGet('paid_commit_journal'),generation:await idbGet(pointer),appState:await idbGet('appState')};});
 const casAttempt=await raceB.page.evaluate(async({terms,approval})=>{__tabStale=false;let writerCalls=0,error='';const original=paidCommitWriteAtomic;paidCommitWriteAtomic=async(...args)=>{writerCalls++;return original(...args);};validateCommercialApproval=async({commercialApproval})=>Object.freeze({receiptId:commercialApproval.receiptId,nonce:'nonce_missed_broadcast',serverNowKst:'2026-08-31T12:00:00+09:00',verifyExpiresAtKst:'2026-08-31T12:01:00+09:00',useBeforeMonotonicMs:Number.MAX_SAFE_INTEGER});try{await transitionAptOrderWithGate({orderId:'critical_order',targetState:'work',commercialTerms:terms,commercialApproval:approval});}catch(e){error=String(e.code||e.message||e);}finally{paidCommitWriteAtomic=original;}return{writerCalls,error,consumed:Array.from(__paidApprovalConsumptions)};},{terms:TERMS,approval:{...receipt('critical_order'),receiptId:'receipt_critical_cas'}});
 const raceAfterCas=await raceA.page.evaluate(async()=>{const pointer=await idbGet('paid_commit_pointer');return{pointer,journal:await idbGet('paid_commit_journal'),generation:await idbGet(pointer),appState:await idbGet('appState')};});
 await raceB.page.reload({waitUntil:'domcontentloaded'});await raceB.page.waitForFunction(()=>window.__hjRestoreDone);await raceB.page.evaluate(()=>Promise.resolve(window.__hjRestoreDone));const rebased=await raceB.page.evaluate(async({terms,approval})=>{validateCommercialApproval=async({commercialApproval})=>Object.freeze({receiptId:commercialApproval.receiptId,nonce:'nonce_rebased_fresh',serverNowKst:'2026-08-31T12:00:00+09:00',verifyExpiresAtKst:'2026-08-31T12:01:00+09:00',useBeforeMonotonicMs:Number.MAX_SAFE_INTEGER});let error='';try{await transitionAptOrderWithGate({orderId:'critical_order',targetState:'work',commercialTerms:terms,commercialApproval:approval});}catch(e){error=String(e.code||e.message||e);}const pointer=await idbGet('paid_commit_pointer'),generation=await idbGet(pointer);return{error,notes:generation&&generation.notes,status:generation&&generation.aptOrders.find(o=>o.id==='critical_order').status};},{terms:TERMS,approval:{...receipt('critical_order'),receiptId:'receipt_critical_rebased'}});
 const criticalResult={sameBase:raceSeed.pointer===raceLoaded.pointer&&raceSeed.stamp===raceLoaded.stamp,ordinaryRetainsPointer:ordinary.ok&&ordinary.pointerBefore===ordinary.pointerAfter,ordinaryStampAdvanced:ordinary.stamp>raceSeed.stamp,staleBroadcast:staleAttempt.tabStale,staleWriterCalls:staleAttempt.writerCalls,staleRejected:/stale|conflict/i.test(staleAttempt.error),staleAckUnconsumed:!staleAttempt.consumed.some(x=>x.startsWith('receipt_critical_stale|')),staleDbUnchanged:JSON.stringify(raceAfterStale)===JSON.stringify(raceBefore),casWriterCalls:casAttempt.writerCalls,casRejected:/stale|conflict/i.test(casAttempt.error),casAckUnconsumed:!casAttempt.consumed.some(x=>x.startsWith('receipt_critical_cas|')),casDbUnchanged:JSON.stringify(raceAfterCas)===JSON.stringify(raceBefore),rebasedSuccess:rebased.error===''&&rebased.status==='work',rebasedPreservesOrdinary:JSON.stringify(rebased.notes)==='[{"id":"fresh-from-a"}]'};
 const criticalExpected={sameBase:true,ordinaryRetainsPointer:true,ordinaryStampAdvanced:true,staleBroadcast:true,staleWriterCalls:0,staleRejected:true,staleAckUnconsumed:true,staleDbUnchanged:true,casWriterCalls:1,casRejected:true,casAckUnconsumed:true,casDbUnchanged:true,rebasedSuccess:true,rebasedPreservesOrdinary:true};if(JSON.stringify(criticalResult)!==JSON.stringify(criticalExpected))reviewFailures.push({finding:'Critical 1 same-pointer stale paid CAS',expected:criticalExpected,actual:criticalResult});await raceA.context.close();

 const auditCase=await open(browser,url);const auditResult=await auditCase.page.evaluate(async({terms,approvalA,approvalB})=>{
  clearTimeout(__idbSaveTimer);__idbSaveTimer=null;state._demo=false;state.projects=[];state.files=[];state.quotes=[];state.notes=[];state.schedule=[];state.calendarImports=[];state.aptOrders=[];state.officeIntake={inbox:[],outbox:[],operationalErrors:[],cursor:'',lastSyncAt:'',lastError:''};await idbDel('appState');await idbDel('paid_commit_pointer');await idbDel('paid_commit_journal');__paidCommitPointerKey=null;__paidApprovalConsumptions.clear();let serial=0;validateCommercialApproval=async({commercialApproval})=>Object.freeze({receiptId:commercialApproval.receiptId,nonce:'nonce_audit_'+(++serial),serverNowKst:'2026-08-31T12:00:00+09:00',verifyExpiresAtKst:'2026-08-31T12:01:00+09:00',useBeforeMonotonicMs:Number.MAX_SAFE_INTEGER});
  await executePaidWorkGate({commandKind:'create-order',subjectType:'aptOrder',subjectId:'audit_order',targetState:'visit',commercialTerms:terms,commercialApproval:approvalA,createDraft:Object.freeze({id:'audit_order',state:'visit'})});
  let release;const blocker=withAppStateWriteLock(()=>new Promise(resolve=>{release=resolve;})),transition=transitionAptOrderWithGate({orderId:'audit_order',targetState:'work',commercialTerms:terms,commercialApproval:approvalB});await new Promise(resolve=>setTimeout(resolve,0));const replacement=updateCommercialTerms('audit_order',{...terms,quotedAmount:310000});release();await blocker;await transition;await replacement;const order=state.aptOrders.find(o=>o.id==='audit_order'),main={active:order.commercialApproval,auditCount:order.commercialApprovalAudit.length,auditedReceipt:order.commercialApprovalAudit.at(-1).previousApproval&&order.commercialApprovalAudit.at(-1).previousApproval.receiptId,status:order.status};
  const originalIssue=issueCommercialApproval,originalGate=executePaidWorkGate,originalTransition=transitionAptOrderWithGate;issueCommercialApproval=async()=>{throw Error('terms update called issue');};executePaidWorkGate=async()=>{throw Error('terms update called gate');};transitionAptOrderWithGate=async()=>{throw Error('terms update called transition');};let isolatedError='';try{await updateCommercialTerms('audit_order',{...terms,quotedAmount:320000});}catch(e){isolatedError=String(e.message||e);}finally{issueCommercialApproval=originalIssue;executePaidWorkGate=originalGate;transitionAptOrderWithGate=originalTransition;}return{...main,isolatedError};
 },{terms:TERMS,approvalA:{...receipt('audit_order'),receiptId:'receipt_audit_A'},approvalB:{...receipt('audit_order'),receiptId:'receipt_audit_B'}});const auditExpected={active:null,auditCount:1,auditedReceipt:'receipt_audit_B',status:'work',isolatedError:''};if(JSON.stringify(auditResult)!==JSON.stringify(auditExpected))reviewFailures.push({finding:'Important 1 candidate-local approval audit',expected:auditExpected,actual:auditResult});await auditCase.context.close();

 const repairCase=await open(browser,url);const repairKinds=['missing-journal','malformed-journal','missing-generation','malformed-generation','timestamp-mismatch'],repairResults=[];
 for(let index=0;index<repairKinds.length;index++){const kind=repairKinds[index],key='paid_commit_generation:repair_'+kind.replaceAll('-','_');await repairCase.page.evaluate(async({kind,key,index})=>{clearTimeout(__idbSaveTimer);__idbSaveTimer=null;state._demo=false;state.projects=[];state.files=[];state.quotes=[];state.notes=[];state.schedule=[];state.calendarImports=[];state.aptOrders=[];state.officeIntake={inbox:[],outbox:[],operationalErrors:[],cursor:'',lastSyncAt:'',lastError:''};const all=await new Promise((resolve,reject)=>{const o=indexedDB.open('hyeonjang-db',1);o.onerror=()=>reject(o.error);o.onsuccess=()=>{const db=o.result,tx=db.transaction('kv','readonly'),r=tx.objectStore('kv').getAllKeys();r.onsuccess=()=>{db.close();resolve(r.result.map(String));};r.onerror=()=>reject(r.error);};});for(const old of all.filter(x=>x.startsWith(PAID_COMMIT_GENERATION_PREFIX)))await idbDel(old);await idbDel('paid_commit_journal');const legacy=serializeData();legacy.savedAt=`2026-08-31T01:00:0${index}.000Z`;legacy.notes=[{id:'fallback-'+kind}];const journal={schemaVersion:1,current:key,previous:null,committedAt:legacy.savedAt,generations:[key],maxGenerations:PAID_COMMIT_MAX_GENERATIONS},generation=structuredClone(legacy);await idbSet('appState',legacy);await idbSet('paid_commit_pointer',key);if(kind!=='missing-journal')await idbSet('paid_commit_journal',kind==='malformed-journal'?{bad:true}:journal);if(kind!=='missing-generation')await idbSet(key,kind==='malformed-generation'?{bad:true}:{...generation,savedAt:kind==='timestamp-mismatch'?'2026-08-31T01:00:59.000Z':generation.savedAt});},{kind,key,index});await repairCase.page.reload({waitUntil:'domcontentloaded'});await repairCase.page.waitForFunction(()=>window.__hjRestoreDone);await repairCase.page.evaluate(()=>Promise.resolve(window.__hjRestoreDone));const saved=await repairCase.page.evaluate(async({kind,key})=>{state._demo=false;state.notes=[{id:'repaired-'+kind}];let ok=false,error='';try{ok=await guardedPersistCurrentState();}catch(e){error=String(e.message||e);}return{source:window.__hjRestoreSource,ok,error,pointer:await idbGet('paid_commit_pointer'),journal:await idbGet('paid_commit_journal'),generation:await idbGet(key),app:await idbGet('appState')};},{kind,key});await repairCase.page.reload({waitUntil:'domcontentloaded'});await repairCase.page.waitForFunction(()=>window.__hjRestoreDone);await repairCase.page.evaluate(()=>Promise.resolve(window.__hjRestoreDone));const survived=await repairCase.page.evaluate(kind=>({notes:state.notes,source:window.__hjRestoreSource}),kind);repairResults.push({kind,source:saved.source,ok:saved.ok,error:saved.error,metadataCleared:saved.pointer===undefined&&saved.journal===undefined&&saved.generation===undefined,appSaved:JSON.stringify(saved.app&&saved.app.notes)===JSON.stringify([{id:'repaired-'+kind}]),reloadSaved:JSON.stringify(survived.notes)===JSON.stringify([{id:'repaired-'+kind}])});}
 const concurrentRepair=await repairCase.page.evaluate(async()=>{const key='paid_commit_generation:repair_concurrent',legacy=serializeData();legacy.savedAt='2026-08-31T01:01:00.000Z';legacy.notes=[{id:'fallback-concurrent'}];await idbSet('appState',legacy);await idbSet('paid_commit_pointer',key);await idbSet('paid_commit_journal',{bad:'observed'});await idbSet(key,legacy);return key;});await repairCase.page.reload({waitUntil:'domcontentloaded'});await repairCase.page.waitForFunction(()=>window.__hjRestoreDone);await repairCase.page.evaluate(()=>Promise.resolve(window.__hjRestoreDone));const concurrentRepairResult=await repairCase.page.evaluate(async key=>{await idbSet('paid_commit_journal',{bad:'concurrent-change'});const before={pointer:await idbGet('paid_commit_pointer'),journal:await idbGet('paid_commit_journal'),generation:await idbGet(key),app:await idbGet('appState')};state._demo=false;state.notes=[{id:'must-not-save'}];let ok=false,error='';try{ok=await guardedPersistCurrentState();}catch(e){error=String(e.message||e);}const after={pointer:await idbGet('paid_commit_pointer'),journal:await idbGet('paid_commit_journal'),generation:await idbGet(key),app:await idbGet('appState')};return{ok,error,unchanged:JSON.stringify(before)===JSON.stringify(after)};},concurrentRepair);const repairOk=repairResults.every(row=>row.source==='legacy-appState'&&row.ok&&row.error===''&&row.metadataCleared&&row.appSaved&&row.reloadSaved)&&concurrentRepairResult.ok===false&&concurrentRepairResult.unchanged;if(!repairOk)reviewFailures.push({finding:'Important 2 exact corrupt-metadata CAS repair',expected:'all 5 corrupt fixtures repair and survive reload; concurrent metadata change returns false unchanged',actual:{repairResults,concurrentRepairResult}});await repairCase.context.close();

 const isolationCase=await open(browser,url);const isolationResult=await isolationCase.page.evaluate(async()=>{clearTimeout(__idbSaveTimer);__idbSaveTimer=null;state._demo=false;state.projects=[];state.files=[];state.quotes=[];state.notes=[];state.schedule=[];state.calendarImports=[];state.aptOrders=[];const canonical={inbox:[{nested:{value:1}}],outbox:[{payload:{value:1}}],operationalErrors:[{code:'x'}],cursor:'c',lastSyncAt:'2026-08-31T00:00:00.000Z',lastError:'none'},withUnknown={...canonical,unknown:'drop-me'},snapshot=officeIntakeSnapshot(withUnknown);withUnknown.inbox[0].nested.value=2;const cloneResult={keys:Object.keys(snapshot),deepValue:snapshot.inbox[0].nested.value,hasUnknown:Object.hasOwn(snapshot,'unknown')},fixtures=[['office_ops_token','inbox'],['office_ops_cache','outbox'],['commercial_approval_token','errors'],['paid_commit_pointer','deep']],fixtureResults=[];
  state.officeIntake={inbox:[],outbox:[],operationalErrors:[],cursor:'',lastSyncAt:'',lastError:''};const clean=serializeData();for(const [key,location] of fixtures){const nested=structuredClone(clean);if(location==='inbox')nested.officeIntake.inbox=[{[key]:'forbidden'}];if(location==='outbox')nested.officeIntake.outbox=[{payload:{[key]:'forbidden'}}];if(location==='errors')nested.officeIntake.operationalErrors=[{details:{[key]:'forbidden'}}];if(location==='deep')nested.officeIntake.inbox=[{details:{deeper:{[key]:'forbidden'}}}];state.officeIntake=structuredClone(nested.officeIntake);let serializerRejected=false,paidRejected=false,legacyRejected=false;try{serializeData();}catch(_){serializerRejected=true;}try{validatePaidSerializedState(nested);}catch(_){paidRejected=true;}try{validateLegacyAppState(nested);}catch(_){legacyRejected=true;}const pointer='paid_commit_generation:nested_'+fixtureResults.length;await idbSet('appState',nested);await idbSet('paid_commit_pointer',pointer);await idbSet('paid_commit_journal',{bad:true});await idbSet(pointer,{bad:true});const resolved=await resolvePaidCommitState(),resolvedText=JSON.stringify(resolved.data||null);fixtureResults.push({key,serializerRejected,paidRejected,legacyRejected,resolverRejected:!resolvedText.includes('forbidden')});await idbDel(pointer);}
  const representative=structuredClone(clean);representative.officeIntake.inbox=[{office_ops_token:'forbidden'}];state.officeIntake=structuredClone(representative.officeIntake);await idbDel('appState');await idbDel('paid_commit_pointer');await idbDel('paid_commit_journal');await idbDel('hj_snaps');const snapshotOk=await hjSnapshot('forbidden ownership',true,true);let guardRejected=false,paidWriteRejected=false;try{await guardedPersistCurrentState();}catch(_){guardRejected=true;}try{await paidCommitWriteAtomic(representative,null,'paid_commit_generation:forbidden_probe');}catch(_){paidWriteRejected=true;}const stored={app:await idbGet('appState'),generation:await idbGet('paid_commit_generation:forbidden_probe'),snaps:await idbGet('hj_snaps')};return{cloneResult,fixtureResults,snapshotRejected:!snapshotOk,guardRejected,paidWriteRejected,noStoredForbidden:!JSON.stringify(stored).includes('forbidden')};});
 const isolationExpected={keys:['inbox','outbox','operationalErrors','cursor','lastSyncAt','lastError'],deepValue:1,hasUnknown:false};const isolationOk=JSON.stringify(isolationResult.cloneResult)===JSON.stringify(isolationExpected)&&isolationResult.fixtureResults.every(row=>row.serializerRejected&&row.paidRejected&&row.legacyRejected&&row.resolverRejected)&&isolationResult.snapshotRejected&&isolationResult.guardRejected&&isolationResult.paidWriteRejected&&isolationResult.noStoredForbidden;if(!isolationOk)reviewFailures.push({finding:'Important 3 exact/deep OfficeIntake ownership isolation',expected:{cloneResult:isolationExpected,allFixturesRejected:true,snapshotRejected:true,guardRejected:true,paidWriteRejected:true,noStoredForbidden:true},actual:isolationResult});await isolationCase.context.close();

 assert.deepEqual(reviewFailures,[],'Task 3 fix round 1 review findings must all be closed');
 await a.context.close();console.log('PASS  native paid commit reload and legacy schema compatibility');
}finally{await browser.close();await new Promise(r=>s.close(r));}})().catch(e=>{console.error('FAIL',e&&e.stack||e);process.exitCode=1;});
